rachael_censuales/GIT.html
rachael_censuales/helpers/GIT_SHEET.md
rachael_censuales/helpers/HTML_SHEET.md
rachael_censuales/lessons/GIT.md
rachael_censuales/lessons/HTML.md
rachael_censuales/lessons/MARKDOWN.md
rachael_censuales/projects/DICTIONARY.md
rachael_censuales/projects/SHEETSTORM.html

There were some error with HTML language and I fixed it.

Code html fixed

---

flavio_leotta/DIZIONARIODELCODER.md
flavio_leotta/git.html
flavio_leotta/gitlezione.md
flavio_leotta/htmldefinizioniecomandi.md
flavio_leotta/indice.html
flavio_leotta/lezionegitriccardo.md
flavio_leotta/markdown.html
flavio_leotta/markdownlezione.md
flavio_leotta/thefilefor.html

flavio_leotta

---

davide_damico/HOMEWORKS.md
davide_damico/general_notes/DAYBYDAY.md
davide_damico/general_notes/GIT_COMMANDS.md
davide_damico/general_notes/HOMEWORKS.md
davide_damico/general_notes/NOTES.md
davide_damico/lesson11.04/DICTIONARY.md
davide_damico/lesson16.04/html-files/GIT-IN-HTML_SHEET.html
davide_damico/lesson16.04/html-files/GITHUB-IN-HTML_SHEET.html
davide_damico/lesson16.04/html-files/HTML-DESCRIPTION-PAGE.html
davide_damico/lesson16.04/html-files/MAINPAGE-HTML-GIT-MD.html
davide_damico/lesson16.04/html-files/MARKDOWN-IN-HTML_SHEET.html
davide_damico/lesson16.04/markdown-files/HTML_DESCRIPTION_SHEET.md
davide_damico/lesson16.04/markdown-files/HTML_TAGS_SHEET.md
davide_damico/online-lesson10.04/GITHUB_SHEET.md
davide_damico/online-lesson10.04/GIT_SHEET.md
davide_damico/online-lesson10.04/MARKDOWN_SHEET.md

Davide D'Amico

---

andrea_marchese/html/git.html
andrea_marchese/html/git_comandi.html
andrea_marchese/html/github.html
andrea_marchese/html/html_lesson.html
andrea_marchese/html/markdown.html
andrea_marchese/index.html

ho solo modificato la mia cartella di partenza, ho sbagliato a pushare sul main

updated files from old repo

---

antonio_marino/html/git.html
antonio_marino/html/github.html
antonio_marino/html/html-spiegazione.html
antonio_marino/html/index.html
antonio_marino/html/markdown.html
antonio_marino/html/termini-tecnici.html
antonio_marino/lessons/GIT.md
antonio_marino/lessons/GITHUB.md
antonio_marino/lessons/MARKDOWN.md
antonio_marino/lessons/TERMINITECNICI.md

aggiungo il mio branch con dentro le cartelle 'html', 'lessons', e 'projects'

---

nicholas_arato/helpers/GIT_SHEET.md
nicholas_arato/helpers/HTML_SHEET.md
nicholas_arato/lessons/GIT.md
nicholas_arato/lessons/MARKDOWN.md
nicholas_arato/projects/DICTIONARY.md
nicholas_arato/projects/summary.html

1. Addition of updated information for:
- lessons
- projects
- cheat sheets
2. Replaced filler text with actual research text

docs(nicholas_arato): addition of updated information for cheat sheets, projects and lessons

---

sofia_liggio/html_files/css.html
sofia_liggio/html_files/index.html
sofia_liggio/papers/CSS.md
sofia_liggio/tags_and_commands/CSS_COMMANDS.md

A paper with base information about CSS system.

docs (sofia_liggio): added CSS base info

---

raffaele_scala/html_project/languages/css.html
raffaele_scala/html_project/languages/html_research.html
raffaele_scala/html_project/languages/markdown_research.html
raffaele_scala/index.html

Fixed href functionality to navigate between files.

feat(raffaele_scala): Added CSS-related files.

---

christian_esposito/HTML/helpers/css_sheet.html
christian_esposito/HTML/index.html
christian_esposito/HTML/lesson/css.html
christian_esposito/MD/helpers/CSS_SHEET.md
christian_esposito/MD/lesson/CSS.md

add new file docs md CSS AND CSS_SHEET
add new feature two page html

Christian Esposito CSS

---

flavio_leotta/HTML/lessons/document.html
flavio_leotta/HTML/lessons/windows.html

please merge this and my previous commit

feat(flavio_leotta): created html file for #windows and  #document

---

rachael_censuales/projects/javascript/dropdown.html
rachael_censuales/projects/javascript/dropdown.js
rachael_censuales/projects/javascript/hideshow.html
rachael_censuales/projects/javascript/hideshow.js
rachael_censuales/projects/javascript/stylefile.html
rachael_censuales/projects/javascript/stylefile.js

exercises completed. 
difficulty points: the "menu.value" and the "switch" element for the dropdown menu with differents background colors

Javascript exercises

---

.github/pull_request_template.md
src/rachael_censuales/projects/group_generator/script.js
src/rachael_censuales/website/lessons/javascript.html

feat(config): modifie files

---

src/samuele_salica/exercises/29april/changebg.html
src/samuele_salica/exercises/29april/changebg.js
src/samuele_salica/exercises/29april/coloreparagrafo.html
src/samuele_salica/exercises/29april/coloreparagrafo.js
src/samuele_salica/exercises/29april/delete.css
src/samuele_salica/exercises/29april/deletebutton.html
src/samuele_salica/exercises/29april/deletebutton.js
src/samuele_salica/exercises/29april/paragrafo.html
src/samuele_salica/exercises/29april/paragrafo.js
src/samuele_salica/exercises/30april/esercizi.css
src/samuele_salica/exercises/30april/esercizi.html
src/samuele_salica/exercises/30april/esercizi.js
src/samuele_salica/exercises/7 maggio/esercizio.js
src/samuele_salica/exercises/7 maggio/randomizer/randomizer.html
src/samuele_salica/exercises/7 maggio/randomizer/randomizer.js
src/samuele_salica/exercises/8 maggio/esercizi.md
src/samuele_salica/exercises/9 maggio/todolist.html
src/samuele_salica/exercises/9 maggio/todolist.js
src/samuele_salica/lessons/JAVASCRIPT.md

docs(lesson): add exercises folder and upgrade js lessons

---

src/gabriele_lore/lessons/OOP.md

Scritto il file .md sulla OOP.

docs(gabriele_lore): Added OOP paper

---

src/gabriele_lore/execirses/javascript/contatore.html
src/gabriele_lore/execirses/javascript/erase.html

fix(gabriele_lore): fixed code

---

src/christian_esposito/HTML/helpers/git_command.html
src/christian_esposito/HTML/helpers/git_flows.html
src/christian_esposito/HTML/helpers/markdown.html
src/christian_esposito/HTML/helpers/tag_html.html
src/christian_esposito/HTML/lesson/css.html
src/christian_esposito/HTML/lesson/css_om.html
src/christian_esposito/HTML/lesson/dom.html
src/christian_esposito/HTML/lesson/git.html
src/christian_esposito/HTML/lesson/html.html
src/christian_esposito/HTML/lesson/markdown.html
src/christian_esposito/challenge/random_groupe.js
src/christian_esposito/esercizi/javascript/09Magg2024/script.js
src/christian_esposito/esercizi/javascript/29_04_2024/index.js
src/christian_esposito/esercizi/javascript/30_04_2024/index.html
src/christian_esposito/esercizi/javascript/30_04_2024/main.js
src/christian_esposito/index.html
src/christian_esposito/project_web/html/page/lesson/css.html
src/christian_esposito/project_web/html/page/lesson/git.html

fix(exercise): fix divergent format

---

src/flavio_leotta/HTML/helpers/markdown.html
src/flavio_leotta/HTML/lessons/arrayoperatoriandmore.html
src/flavio_leotta/HTML/lessons/git.html
src/flavio_leotta/HTML/projects/es10/es10.html
src/flavio_leotta/HTML/projects/es11/es11.html
src/flavio_leotta/HTML/projects/es13/es13.html
src/flavio_leotta/HTML/projects/es6/es6.js
src/flavio_leotta/HTML/projects/es7/es7.html
src/flavio_leotta/HTML/projects/es9/es9.html
src/flavio_leotta/HTML/projects/esdropdown/drdown.html
src/flavio_leotta/HTML/projects/estodolist/todolist.js
src/flavio_leotta/HTML/projects/primoes.html
src/flavio_leotta/HTML/website/aiuti.html
src/flavio_leotta/HTML/website/filecssflavio/testfilefor.css
src/flavio_leotta/HTML/website/lezioni.html

feat(config): corrected every error exept in three file

---

src/francesco_serauto/project/ws-code-01/website/html/docs.html
src/francesco_serauto/project/ws-code-02/dashboard/docs/dom.html
src/francesco_serauto/project/ws-code-02/dashboard/exercises/exercise_1.html
src/francesco_serauto/project/ws-code-02/js/exercise_1.js

fix(website): fix format , fix eslint

---

src/davide_damico/exercises/exercise1/script.js
src/davide_damico/exercises/exercise2/scripts.js
src/davide_damico/exercises/exercise3/scripts.js
src/davide_damico/exercises/exercise5/script.js
src/davide_damico/exercises/website_exercise/website/html/dom.html
src/davide_damico/exercises/website_exercise/website/html/git.html
src/davide_damico/general_notes/DAYBYDAY.md
src/davide_damico/general_notes/NOTES.md
src/davide_damico/lessons/js_files/exempleLessons.js

Correzione dei file js e html , la semantica e creazione dell'esercizio Impiccato

fix(exercise): js and html files fixed

---

src/gabriele_lore/projects/task-list/script.js

feat(gabriele_lore): Created task list script

---

src/gabriele_lore/projects/tris/script.js

Codicedel gioco tris.
Quando si crea un oggetto dà errore

feat(gabriele_lore): Created js tris file

---

src/davide_damico/helpers/helpers_in_md/OBJECT_ORIENTED_PROGRAMMING_OOP_SHEET.md
src/davide_damico/lessons/markdown_files/OBJECT_ORIENTED_PROGRAMMING_OOP_DESCRIPTION.md

Commit della creazione dello sheet e della description di OOP

Discovery OOP And Creation File Sheet

---

src/raffaele_scala/exercise/esercizio_impiccato/script.js
src/raffaele_scala/exercise/esercizio_tris/script.js
src/raffaele_scala/exercise/to_do_list/script.js
src/raffaele_scala/lessons/OOP.md

docs(lesson): aggiunto file md su l'OOP

---

src/adriano_calagna/lessons/OOP.md
src/adriano_calagna/website/html/strumenti/impiccatos.html
src/adriano_calagna/website/html/strumenti/prova impiccato.html
src/adriano_calagna/website/js/impiccato.js
src/adriano_calagna/website/js/impiccatos.js

feat(exercise): aggiunto nuovo file

---

src/davide_damico/exercises/exercise5/script.js
src/davide_damico/lessons/js_files/exempleLessons.js

Fix dei problemi ricevuti con test:lint

fix(config): fixe js syntax errors

---

src/giovanni_larosa/index.html
src/giovanni_larosa/lessons/OOP.MD
src/giovanni_larosa/lessons/OPERATORI.MD
src/giovanni_larosa/primo progetto htm/paginamarkdown.html
src/giovanni_larosa/website/document.html
src/giovanni_larosa/website/git.html
src/giovanni_larosa/website/gitsheet.html
src/giovanni_larosa/website/html.html
src/giovanni_larosa/website/htmlsheet.html
src/giovanni_larosa/website/javascript.html
src/giovanni_larosa/website/lessons.html
src/giovanni_larosa/website/markdown.html
src/giovanni_larosa/website/markdownsheet.html
src/giovanni_larosa/website/window.html

docs(lesson): aggiunte lezioni oop e operatori

---

src/andrea_marchese/exercises/randomizer/style.css
src/flavio_leotta/HTML/website/aiuti.html

feat(config): fix js errors hopefully

---

src/davide_damico/exercises/exercise4/script.js

Ho finito il group randomizer che non avevo ancora terminato

feat(exercise): randomizer group finished

---

src/sofia_liggio/helpers/JAVASCRIPT_COMMANDS.md
src/sofia_liggio/lessons/OOP.md
src/sofia_liggio/sofia_esercitazioni/array.js
src/sofia_liggio/sofia_esercitazioni/esercizi_personali.js
src/sofia_liggio/website/javascript/hangman.js

feat(lesson): fixed syntax and added discovery

---

src/giuseppe_savelli/DIZIONARIO.md
src/giuseppe_savelli/ESERCIZIHTML/git.html
src/giuseppe_savelli/ESERCIZIHTML/git_sheet.html
src/giuseppe_savelli/ESERCIZIHTML/index.html
src/giuseppe_savelli/ESERCIZIHTML/markdown.html
src/giuseppe_savelli/ESERCIZIJAVASCRIPT/esercizio1.js
src/giuseppe_savelli/ESERCIZIJAVASCRIPT/example.js
src/giuseppe_savelli/ESERCIZIJAVASCRIPT/hangman.js
src/giuseppe_savelli/ESERCIZIJAVASCRIPT/tris.js
src/giuseppe_savelli/LESSONS/Git.md
src/giuseppe_savelli/LESSONS/HTML.html
src/giuseppe_savelli/LESSONS/Javascript.md
src/giuseppe_savelli/LESSONS/Markdown.md
src/giuseppe_savelli/LESSONS/oopjavascript.md
src/giuseppe_savelli/PROJECT/DIZIONARIO.md
src/giuseppe_savelli/PROJECT/SOUNDBARS.md

docs(website): i added documentation

---

src/raffaele_scala/lessons/ENTITA.md

docs(lesson): aggiunto file md sulle entita

---

src/davide_damico/lessons/markdown_files/ENTITY_JS_DESCRIPTION.md

Creazione nuovo discovery file sulle entità in javascript

docs(lesson): new file entity_js_description.md

---

src/davide_damico/exercises/website_exercise/new_website/helpers/css-sheet.html
src/davide_damico/exercises/website_exercise/new_website/helpers/git-sheet.html
src/davide_damico/exercises/website_exercise/new_website/helpers/html-sheet.html
src/davide_damico/exercises/website_exercise/new_website/index.html
src/davide_damico/exercises/website_exercise/new_website/lessons/css.html
src/davide_damico/exercises/website_exercise/new_website/lessons/cssom.html
src/davide_damico/exercises/website_exercise/new_website/lessons/dom.html
src/davide_damico/exercises/website_exercise/new_website/lessons/git.html
src/davide_damico/exercises/website_exercise/new_website/lessons/github.html
src/davide_damico/exercises/website_exercise/new_website/lessons/html.html
src/davide_damico/exercises/website_exercise/new_website/lessons/js-const.html
src/davide_damico/exercises/website_exercise/new_website/lessons/js-function.html
src/davide_damico/exercises/website_exercise/new_website/lessons/js-let.html
src/davide_damico/exercises/website_exercise/new_website/lessons/js-var.html
src/davide_damico/exercises/website_exercise/new_website/lessons/markdown.html
src/davide_damico/exercises/website_exercise/new_website/lessons/object-document.html
src/davide_damico/exercises/website_exercise/new_website/lessons/object-window.html
src/davide_damico/exercises/website_exercise/new_website/navbar/cheat-sheet.html
src/davide_damico/exercises/website_exercise/new_website/navbar/descriptions.html
src/davide_damico/exercises/website_exercise/new_website/navbar/vocabulary.html
src/davide_damico/exercises/website_exercise/new_website/style.css

feat(website): new website folder and files to finish and link
